### ISSUE TITLE
[1/4] We finally got Google to fix the import issue

### ISSUE THREAD

**Issue by WillsterJohnson** [importantimport/material-color-utilities#52]
[see this comment](https://github.com/material-foundation/material-color-utilities/pull/61#issuecomment-1433083113)

After months of asking, Google have finally taken an interest in shipping code that is valid for execution. They've added `.js` extensions to their imports! Let's congratulate Google's engineers on implementing what they were taught on day one of their JavaScript education.

I'm not sure if this repo fixes anything else they got wrong, but I've only seen this repo in reference to the imports issue. If that's all this repo fixes, and of course if you trust Google to maintain the use of valid JavaScript, it may be best to direct this lib's users back upstream with a depreaction notice.

**Comment by kwaa** [comment]
The problem still exists. [material-foundation/material-color-utilities#79](https://github.com/material-foundation/material-color-utilities/issues/79)

I tried it locally (pnpm workspace) and it prevented me from installing `@material/material-color-utilities`.

I'll deprecate this fork - once it is fully available upstream, but obviously not yet. so keep the issue open and keep track of news...

**Comment by WillsterJohnson** [comment]
Let's see if we can get rid of the pointless postinstall... https://github.com/material-foundation/material-color-utilities/pull/81
Can't believe Google engineers can't write JavaScript packages.

**Comment by kwaa** [comment]
I really can't understand why upstream doesn't accept external contributions.  Maybe I should consider making some bigger changes (and outside contributions are warmly welcome).

**Comment by rodydavis** [comment]
Please keep in mind the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md) on these issues.

We are not accepting upstream at the moment but can make the changes internally. Just added lots of changes from related issues.

**Comment by kwaa** [comment]
> We are not accepting upstream at the moment but can make the changes internally. Just added lots of changes from related issues.

Apparently upstream was slow to react.  Still doesn't work until latest 0.2.1: I have a question, did they never install this package via npm?

**Comment by rodydavis** [comment]
No we usually depend via sub module.

But it will be fixed on 0.2.2 (change is pending internally and will get pushed out)

**Comment by kwaa** [comment]
Deprecated! Replaced by [`mcu-extra`](https://github.com/importantimport/mcu-extra), which no longer needs to be synchronized with upstream updates.
